name: keycloak_web_auth
description: Web-only Keycloak authentication for Flutter Web using OAuth2/OIDC Authorization Code + PKCE.
version: 0.1.0
homepage: https://github.com/MeIbtihajnaeem/keycloak_web_auth
repository: https://github.com/MeIbtihajnaeem/keycloak_web_auth
issue_tracker: https://github.com/MeIbtihajnaeem/keycloak_web_auth/issues

environment:
  sdk: ^3.9.0
  flutter: ">=3.19.0"

platforms:
  web:

topics:
  - keycloak
  - oauth2
  - oidc
  - flutter-web

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  js: ^0.7.1
  meta: ^1.15.0

dev_dependencies:
  flutter_lints: ^5.0.0
  test: ^1.25.8
  fake_async: ^1.3.1

flutter: {}
